spring:
  profiles:
    active: dev
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/templates/,classpath:/static/,file:D:/temp/ylCardPic
  freemarker:
    settings:
      classic_compatible: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
print:
  name: Samsung SCX-3400 Series

