server:
  port: 8086
spring:
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/static/,classpath:/static/html/,file:D:/temp/ylCardPic
  freemarker:
    settings:
      classic_compatible: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/doctorreimbursement?useUnicode=true&characterEncoding=utf8
        driver-class-name: com.mysql.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.zhangb.**.entity
  configuration: #   sql日志显示，这里使用标准显示
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
 helperDialect: mysql
 reasonable: true
 supportMethodsArguments: true
 params: count=countSql
 rowBoundsWithCount: false

logging:
  level:
    com:
      zhangb:
       family: debug
print:
    name: Samsung SCX-3400 Series